---
- name: install building software and build essentials
  apt:
    name: '{{ item }}'
    state: present
    cache_valid_time: '{{ apt_cache_timeout }}'
    update_cache: yes
  with_items:
    - acl
    - build-essential
    - apt-transport-https
    - python3-apt
