---
- name: Add OpenJDK-r Repository
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'
    state: present
    update_cache: yes

- name: Install OpenJDK8
  apt:
    name: openjdk-8-jdk
    cache_valid_time: '{{ apt_cache_timeout }}'
    update_cache: yes
    state: latest
