---
- name: provision a Fedora 4 instance
  hosts: all
  user: "{{ ansible_user }}"
  vars_files:
    - site_vars.yml
  gather_facts: true
  roles:
    # - { role: postgresql, become: yes, postgres_version: '9.4' }
    - { role: fedora4, become: yes }
